config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stocks do
    resources :prices
  end

  get 'home/index'


  # eg. http://localhost:3000/businesses/sign_in
  devise_for :businesses, path: 'businesses', controllers: {
    sessions: 'businesses/sessions'
  }
  
  resources :businesses


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/admins/index.html.erb
<h1>Admins page</h1>

<% if admin_signed_in? %>
<p>Admin signed in as... <%= current_admin.email %>. Not you?
	<%= link_to "Sign out", destroy_admin_session_path, method: :delete %>
</p>
<% end %>

<ul>

<li><%= link_to 'View business users', businesses_path %></li>

<li><%= link_to 'New Admin', new_admin_path %></li>

<li><%= link_to 'New User', new_business_path %></li>
</ul>

<p>TODO:<br />
	- View a list of all users (admins, business users)<br />
	- create new users<br />
</p>

<h1>Admin users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

	<% @admins.each do |admin| %>
	  <tr>
	    <td><%= admin.email %></td>
	    <td><%= link_to 'Show', admin %></td>
	    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
	    <td><%= link_to 'Destroy', admin, method: :delete,
	                                     data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
</table>