config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stocks do
    resources :prices
  end

  get 'home/index'


  # eg. http://localhost:3000/businesses/sign_in
  devise_for :businesses, path: 'businesses', controllers: {
    sessions: 'businesses/sessions'
  }
  
  resources :businesses


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    encoded_url = URI.encode("https://api.iextrading.com/1.0/stock/#{params[:id]}/price")
    if params[:id] == ''
      @empty = 'Must enter a symbol.'
    elsif
      if params[:id]
        begin
          @stock = parse_uri(open(URI.parse(encoded_url)).read)
        rescue StandardError
          @error = "The stock symbol doesn't exist."
        end
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %> <!--  name of the flash, and its msg -->
<div class="alert alert-warning" role="alert">
  <button class="close" data-dismiss="alert">
    <i class="glyphicon glyphicon-remove"></i>
  </button>
  <%= content_tag(:div, msg) %>
</div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<%= link_to "Stock ticker app", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if business_signed_in? %>
        <li><%= link_to "Stock list", stocks_path %></li>
        <li><%= link_to "Add stock", new_stock_path %></li>
        <li><%= link_to "Sign out", destroy_business_session_path, method: :delete %></li>
        <li><%= link_to "Edit profile", edit_business_registration_path %></li>
        <% else %>
        <li><%= link_to "Sign up", new_business_registration_path %></li>
        <li><%= link_to "Sign in", new_business_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<h1>Check for stock price</h1>
<p>Please sign up/sign in to save stock prices to your list. </p>
	<div class="form-group">
		<%= form_tag root_path, :method => 'GET' do %>
		<%= text_field_tag 'id', nil,
		placeholder: 'Enter company ticker symbol', size: 50, class: "form-control" %>
	</div>

	<div class="actions">
		<%= submit_tag 'Lookup Stock Price', class: "btn btn-primary" %>
	</div>
	<% end %>


	<p>
		<!-- Display stock price -->
		<% if @stock %>
		<%= "Price stock is: $" %>
		  <%= @stock %>
		<% elsif @empty %>
		  <%= @empty %>
		<% end %>

		<!-- Error handling if stock price doesn't exist  -->
		<% if @error %>
		  <%= @error %>
		<% end %>
	</p>