config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stocks do
    resources :prices
  end

  get 'home/index'


  # eg. http://localhost:3000/businesses/sign_in
  devise_for :businesses, path: 'businesses', controllers: {
    sessions: 'businesses/sessions'
  }
  
  resources :businesses


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :stock, required: false
  #validates :ticker_id, presence: true
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_business!
  require 'open-uri'

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all(:order => 'created_at DESC', :limit => 5)

  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
    @stock = Stock.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)
    @stock = Stock.find(params[:stock_id])

    price = open("https://api.iextrading.com/1.0/stock/#{@stock.ticker}/price").read
    @price = @stock.prices.create({price: price})
  # rescue OpenURI::HTTPError => e
  #   puts e # Error message
  #   puts e.io.status # Http Error code
  #   puts e.io.readlines # Http response body

    respond_to do |format|
      if @price.save
        format.html { redirect_to @stock, notice: 'Latest stock price was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @price = Price.find_by(id: params[:id])
    redirect_to stocks_path, notice: 'You are not authorised to view/edit this page.' if @price.nil?
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_price
    @price = Price.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_params
    params.require(:price).permit(:price) if params[:price]
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: @stock, local: true) do |form| %>
<% if price.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

  <ul>
    <% price.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="form-group">
  <%= form.label :ticker %>
  <%= form.text_field :price, id: :price_price, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.text_field :user_id, value: current_business.id, type: :hidden %>
</div>


<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

app/views/prices/new.html.erb
<h1>New Stock</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', stock_prices_path %>

app/views/prices/show.html.erb
<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price.price %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>